/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.Articulos;

import Ventanas.Conexion;
import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.sql.*;
import javax.swing.JOptionPane;
import DataBase.ArticuloLote;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author JIGA_
 */
public class Lote extends javax.swing.JFrame {

    /**
     * Creates new form Lote
     */
    Inventario inventario = new Inventario();
    ArticuloLote articulolote = new ArticuloLote();
    Integer IDArticulo = 0;
    public Lote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CalendarElaboracion = new com.toedter.calendar.JDateChooser();
        CalendarCaducidad = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOTE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Código:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 130, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 130, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha elaboración:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha caducidad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));
        getContentPane().add(CalendarElaboracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 140, -1));
        getContentPane().add(CalendarCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 150, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cafe.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        inventario.setVisible(true);        
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modLote();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        insLote();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       eliLote();
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void insLote(){
        Boolean ValidadNulo = true;        
        if (ValidadNulo){
            updateLote();
            if (validadLote()){
                Conexion conex = new Conexion();
                SimpleDateFormat date = new SimpleDateFormat ("yyyy-MM-dd");
                String FechaElaboracion = date.format(articulolote.getFechaElaboracion());
                String FechaCaducidad = date.format(articulolote.getFecbaCaducidad());
                String Query = "INSERT INTO `articulo_lote`(`ID`, `IDArticulo`, `Activo`, `Codigo`, `Cantidad`, `FechaElaboracion`, `FecbaCaducidad`, `FechaCreacion`, `FechaMod`) VALUES ("
                        + "null,"
                        + "'" + IDArticulo + "',"
                        + "'" + articulolote.getActivo() + "',"
                        + "'" + articulolote.getCodigo() + "',"
                        + "'" + articulolote.getCantidad() + "',"
                        + "'" + FechaElaboracion + "',"
                        + "'" + FechaCaducidad + "',"
                        + "CURRENT_TIMESTAMP,"
                        + "CURRENT_TIMESTAMP)";
                MysqlDataSource dataSource = conex.getConnection();        
                try(Connection conn = dataSource.getConnection()){
                        Statement stmt = conn.createStatement();            
                        stmt.executeUpdate(Query);
                        JOptionPane.showMessageDialog(null,"Agregado Correctamente.");
                        inventario.prepararArticuloLote(inventario.articulo.getId().toString());
                        inventario.fillTablaLote();
                        inventario.setVisible(true);
                        this.dispose();
                }catch(SQLException e){
                        JOptionPane.showMessageDialog(null,e);
                }
            }else{
                JOptionPane.showMessageDialog(null,"El codigo del Lote esta en uso. Favor de proporcionar otro codigo.");
            }
        }else{
            JOptionPane.showMessageDialog(null,"No se puede dejar campos vacios");
        }
    }    
    private void modLote(){
        Boolean ValidadNulo = true;        
        if (ValidadNulo){
            updateLote();
            if (validadLote()){
                Conexion conex = new Conexion();
                SimpleDateFormat date = new SimpleDateFormat ("yyyy-MM-dd");
                String FechaElaboracion = date.format(articulolote.getFechaElaboracion());
                String FechaCaducidad = date.format(articulolote.getFecbaCaducidad()); 
                String Query = "UPDATE `articulo_lote` SET "
                        + "`IDArticulo`='" + IDArticulo + "',"
                        + "`Activo`='" + articulolote.getActivo() + "',"
                        + "`Codigo`='" + articulolote.getCodigo() + "',"
                        + "`Cantidad`='" + articulolote.getCantidad() + "',"
                        + "`FechaElaboracion`='" + FechaElaboracion + "',"
                        + "`FecbaCaducidad`='" + FechaCaducidad + "'"
                        + "WHERE `ID` = '" + articulolote.getId() + "'";
                MysqlDataSource dataSource = conex.getConnection();        
                try(Connection conn = dataSource.getConnection()){
                        Statement stmt = conn.createStatement();            
                        stmt.executeUpdate(Query);
                        JOptionPane.showMessageDialog(null,"Modificado Correctamente.");
                        inventario.prepararArticuloLote(inventario.articulo.getId().toString());
                        inventario.fillTablaLote();
                        inventario.setVisible(true);
                        this.dispose();
                }catch(SQLException e){
                        JOptionPane.showMessageDialog(null,e);
                }
            }else{
                JOptionPane.showMessageDialog(null,"El codigo del Lote esta en uso. Favor de proporcionar otro codigo.");
            }
        }else{
            JOptionPane.showMessageDialog(null,"No se puede dejar campos vacios");
        }
        
    }
    private void eliLote(){
        Conexion conex = new Conexion();
        String Query = "UPDATE `articulo_lote` SET "
                        + "`Activo`='0'"
                        + "WHERE `ID` = '" + articulolote.getId() + "'";
        MysqlDataSource dataSource = conex.getConnection();        
        try(Connection conn = dataSource.getConnection()){
                Statement stmt = conn.createStatement();            
                stmt.executeUpdate(Query);
                JOptionPane.showMessageDialog(null,"Eliminado Correctamente.");
                inventario.prepararArticuloLote(inventario.articulo.getId().toString());
                inventario.fillTablaLote();
                inventario.setVisible(true);
                this.dispose();
        }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
        }
        
    }
    private void updateLote(){
        Integer id = articulolote.getId();
        Short activo = 1;
        String codigo = txtCodigo.getText();
        Long cantidad = Long.parseLong(txtCantidad.getText());
        Date fechaElaboracion = CalendarElaboracion.getDate();
        Date fecbaCaducidad = CalendarCaducidad.getDate();
        Date fechaCreacion = articulolote.getFechaCreacion();
        Date fechaMod = articulolote.getFechaMod();
        fillArticuloLote( id,activo,  codigo,  cantidad,  fechaElaboracion,  fecbaCaducidad,  fechaCreacion,  fechaMod);
        
    }
    public void prepararModLote(String Index){
        Conexion conex = new Conexion();
        String Query = "SELECT * FROM `articulo_lote` WHERE `Activo` = '1' AND `ID` = '"+ Index +"'";
        MysqlDataSource dataSource = conex.getConnection();        
        try(Connection conn = dataSource.getConnection()){
                Statement stmt = conn.createStatement();            
                ResultSet ResulQuery = stmt.executeQuery(Query);
                while(ResulQuery.next()){
                    Integer id = ResulQuery.getInt("ID");
                    short activo = ResulQuery.getShort("Activo");
                    String codigo = ResulQuery.getString("Codigo");
                    long cantidad = ResulQuery.getLong("Cantidad");
                    Date fechaElaboracion = ResulQuery.getDate("FechaElaboracion");
                    Date fecbaCaducidad = ResulQuery.getDate("FecbaCaducidad");
                    Date fechaCreacion = ResulQuery.getDate("FechaCreacion");
                    Date fechaMod = ResulQuery.getDate("FechaMod");
                    fillArticuloLote( id,activo,  codigo,  cantidad,  fechaElaboracion,  fecbaCaducidad,  fechaCreacion,  fechaMod);
                    fillFormulario();
                    btnAgregar.setVisible(false);
                }
        }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
        } 
    }
    public void prepararInsLote(){
        btnEliminar.setVisible(false);
        btnModificar.setVisible(false);        
    }
    private boolean validadLote(){
        
        return true;        
    }
    private void fillArticuloLote(Integer id, short activo, String codigo, long cantidad, Date fechaElaboracion, Date fecbaCaducidad, Date fechaCreacion, Date fechaMod){
        articulolote = new ArticuloLote(id,activo,codigo,cantidad,fechaElaboracion,fecbaCaducidad,fechaCreacion,fechaMod);
    }    
    private void fillFormulario(){
        String Codigo = articulolote.getCodigo();
        Long Cantidad = articulolote.getCantidad();
        Date Elaboracion = articulolote.getFechaElaboracion() ;
        Date Caducidad = articulolote.getFecbaCaducidad();
        txtCodigo.setText(Codigo.toString());
        txtCantidad.setText(Cantidad.toString());
        CalendarElaboracion.setDate(Elaboracion);
        CalendarCaducidad.setDate(Caducidad);
    }
    public void setInventario(Inventario inventariopasado){        
        inventario = inventariopasado;        
    }
    public void setIDArticulo(Integer Index){
        IDArticulo = Index;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser CalendarCaducidad;
    private com.toedter.calendar.JDateChooser CalendarElaboracion;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
