/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Empleados;

import javax.swing.ImageIcon;
import java.sql.*;
import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import javax.swing.JOptionPane;
import DataBase.Empleados;
import Reportes.GenerarReportes;
import Ventanas.Conexion;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author JIGA_
 */
public class RegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUsu
     */
    Empleados empleado = new Empleados();
  
    public RegistroUsuario() {
        initComponents();
  
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/iconcake.png")).getImage());
        this.setLocationRelativeTo(null);
    }      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        CalendarFecha = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNumeroE = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNumeroI = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtCp = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtExtension = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtFacebook = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtIdentificador = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SoftCake Registro de empleados");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de empleados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 600, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarioregistro.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 210));

        btnGuardar.setBackground(new java.awt.Color(153, 51, 0));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 90, 30));

        btnBorrar.setBackground(new java.awt.Color(153, 51, 0));
        btnBorrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 90, 30));

        btnModificar.setBackground(new java.awt.Color(153, 51, 0));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("*Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        txtApellidoP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtApellidoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoPKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 150, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 150, -1));

        jLabel11.setFont(new java.awt.Font("Brush Script MT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SoftCake");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, -1, -1));

        jPanel1.setBackground(new java.awt.Color(113, 22, 2));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS PERSONALES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("*Apellido paterno:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("*Apellido materno:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        txtApellidoM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtApellidoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoMKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 160, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("*Fecha de nacimiento:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));
        jPanel1.add(CalendarFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 840, 100));

        jPanel2.setBackground(new java.awt.Color(113, 22, 2));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "UBICACION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("*Dirección:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtDireccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 350, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("*Número exterior:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        txtNumeroE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNumeroE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroEKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumeroE, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 50, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Interior:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, -1));

        txtNumeroI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNumeroI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroIActionPerformed(evt);
            }
        });
        txtNumeroI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroIKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumeroI, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 110, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("*Colonia:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtColonia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtColonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColoniaKeyTyped(evt);
            }
        });
        jPanel2.add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 350, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("*Código postal:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        txtCp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCpKeyTyped(evt);
            }
        });
        jPanel2.add(txtCp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 50, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("*Estado:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        cmbEstado.setBackground(new java.awt.Color(153, 51, 0));
        cmbEstado.setMaximumRowCount(5);
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Ciudad de México", "Coahuila", "Colima", "Durango", "Estado de México", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas" }));
        cmbEstado.setAutoscrolls(true);
        cmbEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });
        jPanel2.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("*Municipio:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        txtMunicipio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMunicipio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMunicipioKeyTyped(evt);
            }
        });
        jPanel2.add(txtMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 840, 140));

        jPanel3.setBackground(new java.awt.Color(113, 22, 2));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTACTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Celular:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtCelular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });
        jPanel3.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 200, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("*Teléfono:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel3.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 120, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Extensión:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        txtExtension.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtExtension.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExtensionKeyTyped(evt);
            }
        });
        jPanel3.add(txtExtension, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 50, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Email:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 200, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Facebook:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        txtFacebook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFacebook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFacebookKeyTyped(evt);
            }
        });
        jPanel3.add(txtFacebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 240, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 840, 100));

        jPanel4.setBackground(new java.awt.Color(113, 22, 2));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("*Identificador:");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtIdentificador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificadorActionPerformed(evt);
            }
        });
        txtIdentificador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificadorKeyTyped(evt);
            }
        });
        jPanel4.add(txtIdentificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("*Usuario:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel4.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 190, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("*Password:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        jPanel4.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 190, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 840, 90));

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GenerarReporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cafe.jpg"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void prepararModEmpleado(String Identificador){
        btnGuardar.setVisible(false);
        String Ident = Identificador;
        Conexion conex = new Conexion();
        String Query = ("SELECT * FROM `empleados` WHERE `Activo` = 1 AND `Identificador` = '"+Ident+"'");
        MysqlDataSource dataSource = conex.getConnection();        
        try(Connection conn = dataSource.getConnection()){
            Statement stmt = conn.createStatement();            
            ResultSet ResulQuery = stmt.executeQuery(Query);
            if (ResulQuery.next()){
                fillEmpleado(ResulQuery.getInt("id"),ResulQuery.getShort("activo"),ResulQuery.getString("nombre"),ResulQuery.getString("apellidoP"),ResulQuery.getString("apellidoM"),ResulQuery.getDate("fechaNacimiento"),ResulQuery.getString("direccion"),ResulQuery.getString("numExt"),ResulQuery.getString("numInt"),ResulQuery.getString("cp"),ResulQuery.getString("colonia"),ResulQuery.getString("estado"),ResulQuery.getString("municipio"),ResulQuery.getString("telefono"),ResulQuery.getString("ext"),ResulQuery.getString("celular"),ResulQuery.getString("email"),ResulQuery.getString("facebook"),ResulQuery.getString("identificador"),ResulQuery.getString("usuario"),ResulQuery.getString("password"),ResulQuery.getDate("fechaCreacion"),ResulQuery.getDate("fechaMod"));
                fillFormulario();
            }else{
              JOptionPane.showMessageDialog(null,"Problema al encontrar los registros del Empleado.");
              System.exit(0);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error con la conexion de la base de datos: "+e);
        } 
        
    }
    public void prepararInsEmpleado(){
        btnModificar.setVisible(false);
        btnBorrar.setVisible(false);
    }
    
    private void fillFormulario(){        
        txtNombre.setText(empleado.getNombre());
        txtApellidoP.setText(empleado.getApellidoP());
        txtApellidoM.setText(empleado.getApellidoM());
        CalendarFecha.setDate(empleado.getFechaNacimiento());
        txtDireccion.setText(empleado.getDireccion());
        txtNumeroE.setText(empleado.getNumExt());
        txtNumeroI.setText(empleado.getNumInt());
        txtColonia.setText(empleado.getColonia());
        txtCp.setText(empleado.getCp());
        cmbEstado.setSelectedItem(empleado.getEstado());
        txtMunicipio.setText(empleado.getMunicipio());
        txtTelefono.setText(empleado.getTelefono());
        txtExtension.setText(empleado.getExt());
        txtCelular.setText(empleado.getCelular());
        txtEmail.setText(empleado.getEmail());
        txtFacebook.setText(empleado.getFacebook());
        txtIdentificador.setText(empleado.getIdentificador());
        txtUsuario.setText(empleado.getUsuario());
        txtPassword.setText(empleado.getPassword());       
        
    }
    
    
    private void fillEmpleado(Integer id, short activo, String nombre, String apellidoP, String apellidoM, java.util.Date fechaNacimiento, String direccion, String numExt, String numInt, String cp, String colonia, String estado, String municipio, String telefono, String ext, String celular, String email, String facebook, String identificador, String usuario, String password, java.util.Date fechaCreacion, java.util.Date fechaMod){
       empleado = new Empleados( id,  activo,  nombre,  apellidoP,  apellidoM, fechaNacimiento,  direccion,  numExt,  numInt,  cp,  colonia,  estado,  municipio,  telefono,  ext,  celular,  email,  facebook,  identificador,  usuario,  password,  fechaCreacion,  fechaMod); 
    }
    private void updateEmpleado(){
        short Activo = 1;
        empleado.setActivo(Activo);
        empleado.setNombre(txtNombre.getText());
        empleado.setApellidoP(txtApellidoP.getText());
        empleado.setApellidoM(txtApellidoM.getText());
        empleado.setFechaNacimiento(CalendarFecha.getDate());
        empleado.setDireccion(txtDireccion.getText());
        empleado.setNumExt(txtNumeroE.getText());
        empleado.setNumInt(txtNumeroI.getText());
        empleado.setCp(txtCp.getText());
        empleado.setColonia(txtColonia.getText());
        empleado.setEstado(cmbEstado.getSelectedItem().toString());
        empleado.setMunicipio(txtMunicipio.getText());
        empleado.setTelefono(txtTelefono.getText());
        empleado.setExt(txtExtension.getText());
        empleado.setCelular(txtCelular.getText());
        empleado.setEmail(txtEmail.getText());
        empleado.setFacebook(txtFacebook.getText());
        empleado.setIdentificador(txtIdentificador.getText());
        empleado.setUsuario(txtUsuario.getText());
        empleado.setPassword(txtPassword.getText());
    }
    
    private void modEmpleado(){
        if (!"".equals(txtNombre.getText()) && !"".equals(txtApellidoP.getText()) && !"".equals(txtApellidoM.getText()) && CalendarFecha.getDate() !=null && !"".equals(txtDireccion.getText()) && !"".equals(txtNumeroE.getText()) && !"".equals(txtColonia.getText()) && !"".equals(txtCp.getText()) && !"Seleccionar".equals(cmbEstado.getSelectedItem()) && !"".equals(txtMunicipio.getText()) && !"".equals(txtTelefono.getText()) && !"".equals(txtIdentificador.getText()) && !"".equals(txtUsuario.getText()) && !"".equals(txtPassword.getText())){
            updateEmpleado();
            updateEmpleado();
            Calendar Hoy = Calendar.getInstance();
            Calendar Calendario = Calendar.getInstance();
            Calendario.setTime(CalendarFecha.getDate());       
            Integer Ano = Calendario.get(Calendar.YEAR);
            Ano +=18;
            Calendario.set(Calendar.YEAR, Ano);
            if (Calendario.before(Hoy)) {
                if (validarUsuario(empleado.getUsuario(),empleado.getIdentificador())){
                    SimpleDateFormat date = new SimpleDateFormat ("yyyy-MM-dd");
                    String fechanacimiento = date.format(empleado.getFechaNacimiento());        
                    Conexion conex = new Conexion();
                    String Query = ("UPDATE empleados SET "
                            + "Activo='"+ empleado.getActivo() +"',"
                            + "Nombre='"+ empleado.getNombre() +"',"
                            + "ApellidoP='"+ empleado.getApellidoP() +"',"
                            + "ApellidoM='"+ empleado.getApellidoM() +"',"
                            + "FechaNacimiento='"+ fechanacimiento +"',"
                            + "Direccion='"+ empleado.getDireccion() +"',"
                            + "NumExt='"+ empleado.getNumExt() +"',"
                            + "NumInt='"+ empleado.getNumInt() +"',"
                            + "CP='"+ empleado.getCp() +"',"
                            + "Colonia='"+ empleado.getColonia() +"',"
                            + "Estado='"+ empleado.getEstado() +"',"
                            + "Municipio='"+ empleado.getMunicipio() +"',"
                            + "Telefono='"+ empleado.getTelefono() +"',"
                            + "Ext='"+ empleado.getExt() +"',"
                            + "Celular='"+ empleado.getCelular() +"',"
                            + "Email='"+ empleado.getEmail() +"',"
                            + "Facebook='"+ empleado.getFacebook() +"',"
                            + "Identificador='"+ empleado.getIdentificador() +"',"
                            + "Usuario='"+ empleado.getUsuario() +"',"
                            + "Password='"+ empleado.getPassword() +"',"
                            + "FechaMod=CURRENT_TIMESTAMP "
                            + "WHERE ID="+empleado.getId());
                    MysqlDataSource dataSource = conex.getConnection();        
                    try(Connection conn = dataSource.getConnection()){
                        Statement stmt = conn.createStatement();          
                        stmt.executeUpdate(Query);
                        JOptionPane.showMessageDialog(null,"Los datos fueron modificados satisfactoriamente.");
                    }catch(SQLException e){
                        JOptionPane.showMessageDialog(null,"Error con la conexion de la base de datos: "+e);
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"El Usuario o Identificador ya existe, favor de proporcionar uno diferente.");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Menor de 18 Años");  
            }
        }else{
            JOptionPane.showMessageDialog(null,"Los campos marcados con * son obligatorios.");
        }
        
         
        
    }
    
    private boolean validarUsuario(String Usuario,String Identificador){
        Conexion conex = new Conexion();
        String Query = ("SELECT * FROM `empleados` WHERE `Usuario`= '"+Usuario+"' OR `Identificador`= '"+Identificador+"'");
        MysqlDataSource dataSource = conex.getConnection();        
        try(Connection conn = dataSource.getConnection()){
            Statement stmt = conn.createStatement();            
            ResultSet ResulQuery = stmt.executeQuery(Query);
            if (ResulQuery.next()){
                Integer ID1 = ResulQuery.getInt("ID");
                Integer ID2 = empleado.getId();
                if (ID1 == ID2){
                    return true;
                }else{
                   return false; 
                }
            }else{
                return true;
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error con la conexion de la base de datos: "+e);
        } 
        return false;
    }
    
    private void insEmpleado(){       
        if (!"".equals(txtNombre.getText()) && !"".equals(txtApellidoP.getText()) && !"".equals(txtApellidoM.getText()) && CalendarFecha.getDate() !=null && !"".equals(txtDireccion.getText()) && !"".equals(txtNumeroE.getText()) && !"".equals(txtColonia.getText()) && !"".equals(txtCp.getText()) && !"Seleccionar".equals(cmbEstado.getSelectedItem()) && !"".equals(txtMunicipio.getText()) && !"".equals(txtTelefono.getText()) && !"".equals(txtIdentificador.getText()) && !"".equals(txtUsuario.getText()) && !"".equals(txtPassword.getText())){
            updateEmpleado();
            Calendar Hoy = Calendar.getInstance();
            Calendar Calendario = Calendar.getInstance();
            Calendario.setTime(CalendarFecha.getDate());       
            Integer Ano = Calendario.get(Calendar.YEAR);
            Ano +=18;
            Calendario.set(Calendar.YEAR, Ano);
            if (Calendario.before(Hoy)) {
                if (validarUsuario(empleado.getUsuario(),empleado.getIdentificador())){
                    SimpleDateFormat date = new SimpleDateFormat ("yyyy-MM-dd");
                    String fechanacimiento = date.format(empleado.getFechaNacimiento());        
                    Conexion conex = new Conexion();
                    String Query = ("INSERT INTO `empleados` (`Activo`, `Nombre`, `ApellidoP`, `ApellidoM`, `FechaNacimiento`, `Direccion`, `NumExt`, `NumInt`, `CP`, `Colonia`, `Estado`, `Municipio`, `Telefono`, `Ext`, `Celular`, `Email`, `Facebook`, `Identificador`, `Usuario`, `Password`, `FechaCreacion`, `FechaMod`) VALUES ('1','"
                            + empleado.getNombre()+"','"
                            + empleado.getApellidoP()+"','"
                            + empleado.getApellidoM()+"','"
                            + fechanacimiento+"','"
                            + empleado.getDireccion()+"','"
                            + empleado.getNumExt()+"','"
                            + empleado.getNumInt()+"','"
                            + empleado.getCp()+"','"
                            + empleado.getColonia()+"','"
                            + empleado.getEstado()+"','"
                            + empleado.getMunicipio()+"','"
                            + empleado.getTelefono()+"','"
                            + empleado.getExt()+"','"
                            + empleado.getCelular()+"','"
                            + empleado.getEmail()+"','"
                            + empleado.getFacebook()+"','"
                            + empleado.getIdentificador()+"','"
                            + empleado.getUsuario()+"','"
                            + empleado.getPassword()
                            +"',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");            
                    MysqlDataSource dataSource = conex.getConnection();        
                    try(Connection conn = dataSource.getConnection()){
                        Statement stmt = conn.createStatement();          
                        stmt.executeUpdate(Query);
                        JOptionPane.showMessageDialog(null,"Registro realizado exitosamente.");
                    }catch(SQLException e){
                        JOptionPane.showMessageDialog(null,"Error con la conexion de la base de datos: "+e);
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"El Usuario o Identificador ya existe, favor de proporcionar uno diferente.");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Menor de 18 Años");  
            }
        }else{
            JOptionPane.showMessageDialog(null,"Los campos marcados con * son obligatorios.");            
        }               
    }
    
    private void eliEmpleado(){
        updateEmpleado();               
        Conexion conex = new Conexion();
        String Query = ("UPDATE empleados SET Activo='0' WHERE ID="+empleado.getId());
        MysqlDataSource dataSource = conex.getConnection();        
        try(Connection conn = dataSource.getConnection()){
            Statement stmt = conn.createStatement();          
            stmt.executeUpdate(Query);
            JOptionPane.showMessageDialog(null,"El Usuario '"+empleado.getUsuario()+"' Con codigo de empleado "+empleado.getIdentificador()+" fue eliminado satisfactoriamente.");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error con la conexion de la base de datos: "+e);
        }
    }
    
    
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        ControlEmpleados control = new ControlEmpleados();
        control.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked
    
  
    
    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtNumeroIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroIActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        insEmpleado();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();
        if((c<'A'||c>'Z')&&(c !=(char)KeyEvent.VK_SPACE))evt.consume();
        
        int longitud = 50;
        if(txtNombre.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 50 caracteres, intente de nuevo", "Error", 0);
            txtNombre.setText("");
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPKeyTyped
        char c = evt.getKeyChar();
        if(c<'A'||c>'Z')evt.consume();
        
        int longitud = 25;
        if(txtApellidoP.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 25 caracteres, intente de nuevo", "Error", 0);
            txtApellidoP.setText("");
        }
    }//GEN-LAST:event_txtApellidoPKeyTyped

    private void txtApellidoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMKeyTyped
        char c = evt.getKeyChar();
        if(c<'A'||c>'Z')evt.consume();
        
         int longitud = 25;
        if(txtApellidoM.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 25 caracteres, intente de nuevo", "Error", 0);
            txtApellidoM.setText("");
        }
    }//GEN-LAST:event_txtApellidoMKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        char c = evt.getKeyChar();
        if((c<'0'||c>'9')&&(c<'A'||c>'Z')&&(c !=(char)KeyEvent.VK_SPACE))evt.consume();
        
        int longitud = 80;
        if(txtDireccion.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 80 caracteres, intente de nuevo", "Error", 0);
            txtDireccion.setText("");
        }
        
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtNumeroEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroEKeyTyped
         char c = evt.getKeyChar();
        if((c<'0'||c>'9')&&(c<'A'||c>'Z')&&(c !=(char)KeyEvent.VK_SPACE))evt.consume();
        
        int longitud = 10;
        if(txtNumeroE.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 10 caracteres, intente de nuevo", "Error", 0);
            txtNumeroE.setText("");
        }
    }//GEN-LAST:event_txtNumeroEKeyTyped

    private void txtNumeroIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroIKeyTyped
       char c = evt.getKeyChar();
       if((c<'0'||c>'9')&&(c<'A'||c>'Z')&&(c !=(char)KeyEvent.VK_SPACE))evt.consume();
       
       int longitud = 10;
        if(txtNumeroI.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 10 caracteres, intente de nuevo", "Error", 0);
            txtNumeroI.setText("");
        }
       
    }//GEN-LAST:event_txtNumeroIKeyTyped

    private void txtCpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
        
        int longitud = 10;
        if(txtCp.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 10 caracteres, intente de nuevo", "Error", 0);
            txtCp.setText("");
        }
    }//GEN-LAST:event_txtCpKeyTyped

    private void txtColoniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColoniaKeyTyped
         char c = evt.getKeyChar();
        if((c<'0'||c>'9')&&(c<'A'||c>'Z')&&(c !=(char)KeyEvent.VK_SPACE))evt.consume();
        
        int longitud = 25;
        if(txtColonia.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 25 caracteres, intente de nuevo", "Error", 0);
            txtColonia.setText("");
        }
    }//GEN-LAST:event_txtColoniaKeyTyped

    private void txtMunicipioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMunicipioKeyTyped
         char c = evt.getKeyChar();
        if((c<'A'||c>'Z')&&(c !=(char)KeyEvent.VK_SPACE))evt.consume();
        
        int longitud = 25;
        if(txtMunicipio.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 25 caracteres, intente de nuevo", "Error", 0);
            txtMunicipio.setText("");
        }
    }//GEN-LAST:event_txtMunicipioKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
        
        int longitud = 25;
        if(txtTelefono.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 25 caracteres, intente de nuevo", "Error", 0);
            txtTelefono.setText("");
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtExtensionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExtensionKeyTyped
         char c = evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
        
        int longitud = 10;
        if(txtExtension.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 10 caracteres, intente de nuevo", "Error", 0);
            txtExtension.setText("");
        }
    }//GEN-LAST:event_txtExtensionKeyTyped

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
         char c = evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
        
        int longitud = 25;
        if(txtCelular.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 25 caracteres, intente de nuevo", "Error", 0);
            txtCelular.setText("");
        }
    }//GEN-LAST:event_txtCelularKeyTyped

    private void txtFacebookKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFacebookKeyTyped
         char c = evt.getKeyChar();
        if((c<'0'||c>'9')&&(c<'A'||c>'Z'))evt.consume();
        int longitud = 50;
        if(txtFacebook.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 50 caracteres, intente de nuevo", "Error", 0);
            txtFacebook.setText("");
        }
    }//GEN-LAST:event_txtFacebookKeyTyped

    private void txtIdentificadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificadorKeyTyped
       char c = evt.getKeyChar();
       if((c<'0'||c>'9')&&(c<'A'||c>'Z'))evt.consume();
        
        int longitud = 10;
        if(txtIdentificador.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 10 caracteres, intente de nuevo", "Error", 0);
            txtIdentificador.setText("");
        }
    }//GEN-LAST:event_txtIdentificadorKeyTyped

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        char c = evt.getKeyChar();
        if((c<'0'||c>'9')&&(c<'A'||c>'Z'))evt.consume();
        
        int longitud = 5;
        if(txtPassword.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 5 caracteres, intente de nuevo", "Error", 0);
            txtPassword.setText("");
        }
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
         char c = evt.getKeyChar();
        if(c<'A'||c>'Z')evt.consume();
        int longitud = 15;
        if(txtUsuario.getText().length()>=longitud)
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo no puede ser mayor a 15 caracteres, intente de nuevo", "Error", 0);
            txtUsuario.setText("");
        }
        
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modEmpleado();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        eliEmpleado();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed
    
    public boolean verifyEmail (String correo)  {
        //try{
            Pattern pat = null;
            Matcher mat = null;
            pat = Pattern.compile("^[\\w\\-\\_\\+]+(\\.[\\w\\-\\_]+)*@[A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");   
            mat = pat.matcher(correo);
            if(mat.find()){
                return true;
            }else{
            return false;
            }
        //}catch(Exception e){
           // JOptionPane.showMessageDialog(this, e);
         //   return false;
        //}        
    }
    
    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(verifyEmail(txtEmail.getText()))
        {
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Correo incorrecto", "Favor de ingresar un correo valido", JOptionPane.INFORMATION_MESSAGE);
            txtEmail.requestFocus();
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificadorActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GenerarReportes gr = new GenerarReportes();
        gr.ReporteEmpleado(empleado.getId());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser CalendarFecha;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtCp;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtExtension;
    private javax.swing.JTextField txtFacebook;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroE;
    private javax.swing.JTextField txtNumeroI;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
