/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventas;
import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Ventanas.*;
/**
 *
 * @author JIGA_
 */
public class Agregar extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    GenerarVenta GV = new GenerarVenta();
    public Agregar() {
        initComponents();
    }
    
    public void setGenerarVenta(GenerarVenta Ventana){
        GV = Ventana;
    }
    private void limpiarTablaArticulo(){
        DefaultTableModel model = (DefaultTableModel) TablaProductos.getModel();
        int CountRows = model.getRowCount();        
        for (int i = 0; i<CountRows; i++){
            model.removeRow(0);
        } 
    }
    private void agregarRowTablaArticulo(String ID, String Codigo, String Nombre,String Descripcion, String Precio,String Existencia,String Unidad){
        DefaultTableModel mode1TablaProductos = (DefaultTableModel) TablaProductos.getModel();
        mode1TablaProductos.addRow(new Object[]{ID,Codigo,Nombre,Descripcion,Precio,Existencia,Unidad});
    }
     private void limpiarTablaLote(){
        DefaultTableModel model = (DefaultTableModel) TablaLote.getModel();
        int CountRows = model.getRowCount();        
        for (int i = 0; i<CountRows; i++){
            model.removeRow(0);
        } 
    }
    private void agregarRowTablaLote(String ID, String Codigo, String Cantidad, String FechaElaboracion, String FechaCaducidad){
        DefaultTableModel mode1TablaProductos = (DefaultTableModel) TablaLote.getModel();
        mode1TablaProductos.addRow(new Object[]{ID,Codigo,Cantidad,FechaElaboracion,FechaCaducidad});
    }
    private String getQueryBuscar(){
        String Query = "SELECT * FROM `articulo` WHERE `Activo` = '1' ";
        String codigoBuscar;
        String nombreBuscar;
        
        codigoBuscar = txtCodigo.getText();
        nombreBuscar = txtNombre.getText();
        
        if (!"".equals(codigoBuscar)){
            Query +="AND `Codigo` = '" + codigoBuscar + "'";
        }else if(!"".equals(nombreBuscar)){
            Query += "AND `Nombre` LIKE '%" + nombreBuscar + "%'";         
        }           
        return Query;
    }
    
    private String getUnidad(Integer Index){
        String Parametro = "";
        String Query = "SELECT * FROM `articulo_unidad` WHERE `ID` = '" + Index + "'";
        Conexion  conex = new Conexion();
        MysqlDataSource dataSource = conex.getConnection();     
        try(Connection conn = dataSource.getConnection()){
            Statement stmt = conn.createStatement();            
            ResultSet ResulQuery = stmt.executeQuery(Query);
            while(ResulQuery.next()){
               Parametro = ResulQuery.getString("NombreCorto");                
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        } 
        return Parametro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaLote = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Código:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 140, -1));

        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 120, -1));

        btnBuscar.setBackground(new java.awt.Color(153, 51, 0));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Nombre", "Descripción", "Precio", "Existencia", "Unidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 590, 130));

        btnAgregar.setBackground(new java.awt.Color(153, 51, 0));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar productos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        TablaLote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Stock", "Fecha elaboración", "Fecha caducidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaLote);
        if (TablaLote.getColumnModel().getColumnCount() > 0) {
            TablaLote.getColumnModel().getColumn(0).setResizable(false);
            TablaLote.getColumnModel().getColumn(1).setResizable(false);
            TablaLote.getColumnModel().getColumn(2).setResizable(false);
            TablaLote.getColumnModel().getColumn(3).setResizable(false);
            TablaLote.getColumnModel().getColumn(3).setPreferredWidth(150);
            TablaLote.getColumnModel().getColumn(4).setResizable(false);
            TablaLote.getColumnModel().getColumn(4).setPreferredWidth(150);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 280, 590, 120));

        jLabel5.setFont(new java.awt.Font("Brush Script MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SoftCake");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cafe.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Conexion conex = new Conexion();
        String Query = getQueryBuscar();
        MysqlDataSource dataSource = conex.getConnection();        
        try(Connection conn = dataSource.getConnection()){
            Statement stmt = conn.createStatement();            
            ResultSet ResulQuery = stmt.executeQuery(Query);
            limpiarTablaArticulo();
            while(ResulQuery.next()){
                String ID = ResulQuery.getString("ID");
                String Codigo = ResulQuery.getString("Codigo");
                String Nombre = ResulQuery.getString("Nombre");
                String Descripcion = ResulQuery.getString("Descripcion");
                String Precio = ResulQuery.getString("Precio");
                String Existencia = ResulQuery.getString("Existencia");
                String Unidad = getUnidad(ResulQuery.getInt("IDUnidad"));
                agregarRowTablaArticulo(ID,Codigo,Nombre,Descripcion,Precio,Existencia,Unidad);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int TablaLoteRS = TablaLote.getSelectedRow();
        Integer TablaProductoRS = this.TablaProductos.getSelectedRow();
        if (TablaLoteRS > -1 && TablaProductoRS > -1 ){
            String IDArticulo = TablaProductos.getValueAt(TablaProductoRS, 0).toString();
            String IDArticulo_Lote = TablaLote.getValueAt(TablaLoteRS, 0).toString();
            String Codigo = TablaProductos.getValueAt(TablaProductoRS, 1).toString() + "." + TablaLote.getValueAt(TablaLoteRS, 1).toString();
            String Cantidad = "1";
            String Descripcion = TablaProductos.getValueAt(TablaProductoRS, 2).toString();
            String Stock = TablaLote.getValueAt(TablaLoteRS, 2).toString();
            String PrecioUnitario = TablaProductos.getValueAt(TablaProductoRS, 4).toString();            
            GV.agregarRowTablaConceptos(IDArticulo, IDArticulo_Lote,Codigo,Cantidad,Descripcion, Stock, PrecioUnitario);
            GV.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Favor de seleccionar un dato.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        GV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void TablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductosMouseClicked
        int RowSeleccionado = TablaProductos.getSelectedRow();       
        if (RowSeleccionado > -1){	
		String IDArticulo = TablaProductos.getValueAt(RowSeleccionado, 0).toString();
		Conexion conex = new Conexion();
        String Query = "SELECT * FROM `articulo_lote` WHERE  `Activo` = '1' AND `IDArticulo` = '" +IDArticulo+ "'";
        MysqlDataSource dataSource = conex.getConnection();        
        try(Connection conn = dataSource.getConnection()){
            Statement stmt = conn.createStatement();            
            ResultSet ResulQuery = stmt.executeQuery(Query);
            limpiarTablaLote();
            while(ResulQuery.next()){
                String ID = ResulQuery.getString("ID");
                String Codigo = ResulQuery.getString("Codigo");
                String Cantidad = ResulQuery.getString("Cantidad");
                String FechaElaboracion = ResulQuery.getString("FechaElaboracion");
                String FechaCaducidad = ResulQuery.getString("FecbaCaducidad");
                agregarRowTablaLote(ID, Codigo, Cantidad, FechaElaboracion, FechaCaducidad);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
		}else{
            JOptionPane.showMessageDialog(null, "Favor de seleccionar un dato.");
        }
    }//GEN-LAST:event_TablaProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaLote;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
